use_frameworks!

platform :ios, '10.0'

target 'SwiftyVolley_Example' do
  pod 'SwiftyVolley', :path => '../'

  target 'SwiftyVolley_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 4.0.0'
    pod 'Nimble', '~> 9.2.0'
  end
end
